/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PurchaseEntry = IDL.Record({
  'purchaseDate' : IDL.Text,
  'purchaseRate' : IDL.Float64,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'totalPurchaseValue' : IDL.Float64,
});
export const DailySalesEntry = IDL.Record({
  'salesman' : IDL.Text,
  'stockQty' : IDL.Nat,
  'date' : IDL.Text,
  'loadNumber' : IDL.Text,
  'stockValue' : IDL.Float64,
  'daySales' : IDL.Float64,
  'salesValue' : IDL.Float64,
  'totalBills' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPurchase' : IDL.Func([PurchaseEntry], [], []),
  'bulkAddPurchases' : IDL.Func([IDL.Vec(PurchaseEntry)], [], []),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseEntry)], ['query']),
  'getDailyEntry' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(DailySalesEntry)],
      ['query'],
    ),
  'getEntriesByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailySalesEntry)],
      ['query'],
    ),
  'getEntriesByWeek' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailySalesEntry)],
      ['query'],
    ),
  'getPurchases' : IDL.Func([IDL.Text], [IDL.Vec(PurchaseEntry)], ['query']),
  'saveDailyEntry' : IDL.Func([DailySalesEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PurchaseEntry = IDL.Record({
    'purchaseDate' : IDL.Text,
    'purchaseRate' : IDL.Float64,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'totalPurchaseValue' : IDL.Float64,
  });
  const DailySalesEntry = IDL.Record({
    'salesman' : IDL.Text,
    'stockQty' : IDL.Nat,
    'date' : IDL.Text,
    'loadNumber' : IDL.Text,
    'stockValue' : IDL.Float64,
    'daySales' : IDL.Float64,
    'salesValue' : IDL.Float64,
    'totalBills' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPurchase' : IDL.Func([PurchaseEntry], [], []),
    'bulkAddPurchases' : IDL.Func([IDL.Vec(PurchaseEntry)], [], []),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseEntry)], ['query']),
    'getDailyEntry' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(DailySalesEntry)],
        ['query'],
      ),
    'getEntriesByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailySalesEntry)],
        ['query'],
      ),
    'getEntriesByWeek' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailySalesEntry)],
        ['query'],
      ),
    'getPurchases' : IDL.Func([IDL.Text], [IDL.Vec(PurchaseEntry)], ['query']),
    'saveDailyEntry' : IDL.Func([DailySalesEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };